# Generated by Django 5.2.5 on 2025-08-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaivarity',
            name='image',
        ),
    ]
